### ISSUE TITLE
phpCAS error with phpBB 3.2

### ISSUE THREAD

**Issue by devwald** [Getekid/phpbb3-CAS-Auth-plugin#10]
Hello,

I test this plugin with phpBB 3.2
I have this error when i want login with CAS : 

phpCAS error: phpCAS::setFixedServiceURL(): this method should only be called after phpCAS::proxy() in /var/www/phpBB3/ext/getekid/cas/auth/provider/cas.php on line 154

Any idea ?

Thanks.

**Comment by Getekid** [comment]
Hello,

I'll have to look at this to be sure, can you comment out that line and try again? I can provide a patch at some point if needed.

Thank you

**Comment by devwald** [comment]
Hello,

If i comment only this line i have the same error with another line (157, 159 and 160)

But if i comment line 154, 157, 159 and 160 there is no CAS authentification.

Any idea ?

Thanks

![capture d ecran 2017-02-15 a 14 30 47](https://cloud.githubusercontent.com/assets/9694150/22976547/7fc8495c-f38b-11e6-8e1f-47b541027e0f.png)
![capture d ecran 2017-02-15 a 14 28 11](https://cloud.githubusercontent.com/assets/9694150/22976548/7fc8e862-f38b-11e6-8d98-0d3204fd1fdd.png)

**Comment by Getekid** [comment]
I think I found the issue, are you sure in your CAS settings that you have no URI? The plugin assumes there should be one.

If so, then remove the `&& $this->config['cas_uri']` part from line [71](https://github.com/Getekid/phpbb3-CAS-Auth-plugin/blob/master/getekid/cas/auth/provider/cas.php#L71), in other words the line should be

`if ($this->config['cas_host'] && $this->config['cas_port'])`

Let me know if it works as that would mean I need to change it.

Thanks again

**Comment by devwald** [comment]
Yes, i don't have URI
Now, i have this error : 

> [phpBB Debug] PHP Warning: in file [ROOT]/ext/getekid/cas/auth/provider/CAS-1.3.4/CAS/Client.php on line 3167: DOMDocument::loadXML(): Empty string supplied as input
> CAS Authentication failed!
> 
> You were not authenticated.
> 
> You may submit your request again by clicking here.
> 
> If the problem persists, you may contact the administrator of this site.
> Fatal error: Uncaught exception 'CAS_AuthenticationException' in /var/www/phpBB3/ext/getekid/cas/auth/provider/CAS-1.3.4/CAS/Client.php:3169 Stack trace: #0 /var/www/phpBB3/ext/getekid/cas/auth/provider/CAS-1.3.4/CAS/Client.php(1419): CAS_Client->validateCAS20('https://cas.uhb...', '', NULL, false) #1 /var/www/phpBB3/ext/getekid/cas/auth/provider/CAS-1.3.4/CAS/Client.php(1249): CAS_Client->isAuthenticated() #2 /var/www/phpBB3/ext/getekid/cas/auth/provider/CAS-1.3.4/CAS.php(1080): CAS_Client->forceAuthentication() #3 /var/www/phpBB3/ext/getekid/cas/auth/provider/cas.php(158): phpCAS::forceAuthentication() #4 /var/www/phpBB3/phpbb/auth/auth.php(939): getekid\cas\auth\provider\cas->login('', '') #5 /var/www/phpBB3/ext/getekid/cas/event/cas_login_listener.php(74): phpbb\auth\auth->login('', '') #6 [internal function]: getekid\cas\event\cas_login_listener->login_after_cas_redirect(Object(phpbb\event\data), 'core.update_ses...', Object(phpbb\event\dispatcher)) #7 /var/www/phpBB3/vendor/symfony/event-dispatcher/EventDispatcher.p in /var/www/phpBB3/ext/getekid/cas/auth/provider/CAS-1.3.4/CAS/Client.php on line 3169 

PS : now, i'm using version 1.3.4 of phpCAS to do this test

**Comment by Getekid** [comment]
Try to rename the folder "CAS-1.3.4" to "CAS" and it will work, it's the Step 3 in the [Guidelines](https://github.com/Getekid/phpbb3-CAS-Auth-plugin/blob/master/README.md).

**Comment by devwald** [comment]
It's a symbolic link : 

> root@v-dev-fw:/var/www/phpBB3/ext/getekid/cas/auth/provider# ls -alrt
total 28
drwxr-xr-x 3 root root  4096 Feb 15 11:24 ..
drwxr-xr-x 3 root root  4096 Feb 15 14:15 CAS-OLD
lrwxrwxrwx 1 root root     9 Feb 15 14:55 CAS -> CAS-1.3.4
drwxr-xr-x 4 root root  4096 Feb 15 15:06 CAS-1.3.4
-rw-r--r-- 1 root root 10058 Feb 15 15:08 cas.php
drwxr-xr-x 4 root root  4096 Feb 15 15:09 .

**Comment by devwald** [comment]
It's OK with version 1.3.0 of PHPCAS and when i put "/" in CAS URI
![capture d ecran 2017-02-15 a 15 21 04](https://cloud.githubusercontent.com/assets/9694150/22978315/8538ee6c-f392-11e6-86a1-0ee5ed1b30ef.png)

Thanks.

**Comment by devwald** [comment]
t's OK also with version 1.3.4 of PHPCAS and when i put CAS VERSION 2 (in reality we have CAS VERSION 3)
![capture d ecran 2017-02-15 a 15 29 45](https://cloud.githubusercontent.com/assets/9694150/22978650/db332fde-f393-11e6-98a6-ebf92d681429.png)

So you can close this issue.

Thanks.

**Comment by Getekid** [comment]
Apologies, I should have looked at the error more closely.

Great to see it works. I was about to suggest this, can you verify it also works with 1.3.4. ?

Thanks

**Comment by devwald** [comment]
Yes.
Cf. https://github.com/Getekid/phpbb3-CAS-Auth-plugin/issues/10#issuecomment-280025725

**Comment by Getekid** [comment]
Needing version 2 is unexpected as the validation error function is the same for 2 and 3. But good to see it works.

This topic has been a bit off, the original issue was about an error with phpBB 3.2.x but it turned out to be independent. I opened another issue for the URI to be `/` by default, #11 , therefore this one can close.

Best
