### ISSUE TITLE
Extension no more recognized since 0.3

### ISSUE THREAD

**Issue by Jhereck** [Getekid/phpbb3-CAS-Auth-plugin#2]
May be a problem with the "Composer.json" file, cause it gave me an error message when i tried to replace old files with the new ones, without desactivating the extension.

Thanks !

**Comment by Getekid** [comment]
Can you replace the composer.json file with the old one and see if it works? This way we can know for sure it's this file's fault.

Also, 0.3.0 is not meant to update any previous versions so it's better to clear everything from 0.2.0 before you instalI the new one. If you have db access you should also manually delete the 'cas_server', 'cas_port' and 'cas_uri' rows from the config table (this procedure is no longer needed in 0.3.0).

**Comment by Jhereck** [comment]
Tried to replace the composer.json with the old one : the extension is recognized again, but in version 0.2 instead of 0.3, and got an error when trying to go in the "Authentification" menu to set the options ([phpBB Debug] PHP Warning: in file [ROOT]/ext/getekid/cas/auth/provider/cas.php on line 22: require_once(CAS/CAS.php): failed to open stream: No such file or directory)

**Comment by Getekid** [comment]
The error was irrelevant to the absence of the composer, you need to install the phpCAS library for the extension AND the CAS authentication to work. Putting a note about it was planned for 0.5.0 which is now released :) !

Uninstall everything (including db changes as before 0.3.0 the have to be done manually) and install the 0.5.0 version. In this one
1.  The composer issue is fixed!
2.  There are guidelines in the Readme.md about installing phpCAS!
3.  The extension tells you whether you have installed the phpCAS library or not. In worse case you'll get a warning about it and you won't be allowed to enable Cas from the Authentication panel. In any case you won't get any fatal errors!

**Comment by Jhereck** [comment]
Ok installed the new version and setuped CAS connexion : got a blank screen when trying to connect with admin credential (and dunno how to get connected throught CAS...).

So for now i dunno how to get connected back to the forum to try to change things !

**Comment by Getekid** [comment]
Can you access your board?

CAS login is activated when you click the login button, no username or password required.

If you have a CAS admin account then you should be able to login with it and access the ACP to make any changes needed. If not, then you should access the db and change the 'auth_method' value from the config table from 'cas' to 'db.

PS: Since your initial problem is appearently solved, I will close this issue as it is better to discuss new ones on their respective place.

Thank you for your feedback !

**Comment by Jhereck** [comment]
Changed the auth_methodin to db, but still no way to connect to the board...... Blank screen !

**Comment by Getekid** [comment]
Try to clear cache. Since you can't access the board, clear everything in the directory /phpbb3/cache/ !

**Comment by Jhereck** [comment]
Cleared browser cache and /phpbb/cache, still blank screen.

**Comment by Getekid** [comment]
The extension shouldn't have any issues as such. It only applies from the point you click on "Login". Having a blank screen must be remainings of a bad load.

Do you have any error logs? in any case, try from a different browser or -even better- from private browsing. This way you can know for sure if it's the site or something else.

Last I'd recommend to try the extension on a clean install to ensure you will keep getting this problem. From my side it works fine so I need your feedback to find any potential bugs.

**Comment by Jhereck** [comment]
Reinstalling, will tell you if it works on a fresh installation ;)

**Comment by Getekid** [comment]
Great. For reference reasons please open a new issue describing the problem in total.

Thanks again.
