### ISSUE TITLE
Still doesn't work on fresh install

### ISSUE THREAD

**Issue by Jhereck** [Getekid/phpbb3-CAS-Auth-plugin#3]
Ok reinstalled phpbb 3.1.2 and got the same error as before : setuped my CAS server, logged in CAS, tried to click on "Login" on phpbb, and it ask for login and pass like for a db authentication.

When using login/pass, i got a blank screen. So can't log in on the board, again !

It may be a problem with the phpcas library installation or something like that if it works on your board !

**Comment by Jhereck** [comment]
I thought to something : does the plugin automaticly create new account when an user is not registered on phpbb and he tries to log in through CAS ?

Maybe that's the problem in my case !

**Comment by nicocasel** [comment]
Thanks @Jhereck for this issue because I get almost the same:
1) I access to the forum unlogged
2) I login with my CAS login/pwd
3) I am redirected to the CAS validation page ("Your CAS account is ok") during only one second...
4) then I am redirected to the forum login page, asking for a db authentication.

@Getekid : what do you think about it?

**Comment by Getekid** [comment]
First to clarify that just pressing the Login button is enough. CAS can't read your username/password and this is why it redirects you to his server to login. On a next version the form will be delimited to just the button. For now you can just ignore the user/pass text areas.

Redirecting back to the db screen is a bug I plan to fix asap. A temporary workaround is to add
`if (defined('IN_LOGIN') && request_var('mode', '') == 'login')`
`{`
`  phpCAS::forceAuthentication();`
`}`
on auth/provider/cas.php line 71 (before the curly bracket). Still this is kinda messy and doesn't make the plugin as stable as it should be.

@Jhereck, about the blank screen, another thing you could try is commenting line 47 of auth/provider/cas.php . This is just for unblocking your board, as without that command you won't be able to CAS login at all.

**Comment by Jhereck** [comment]
Ok after an other reinstall i will be more precise : currently i'm not redirected to my CAS server login page when i click on the login button !
Is it needed to put the "http://" in the adress of the CAS server ?!

**Comment by Jhereck** [comment]
Tried with "http//", same result : not redirected to my CAS server.....

CAS identification is working with Drupal, so dunno what's going wrong.

**Comment by Getekid** [comment]
Nothing to worry about, if you are already logged in, the CAS server doesn't ask you to login again, so it redirects you back to the form (because of the bug)! CAS login with be again required if you CAS logout.

Try the workaround I mention above and check again or wait for the next version!

**Comment by nicocasel** [comment]
Hi @Getekid ,
I've tried your temp workaround but it does not work better...

**Comment by Getekid** [comment]
Try logging in in your CAS server, then going to the login screen of your board (not the index, but the /ucp.php?mode=login) and then clicking "Login"!

Oh and something that was mentioned before but wasn't clarified (sorry for that, it's important). Authentication can happen ONLY if the user already exists in the db!

**Comment by Jhereck** [comment]
Ok so the fact that users needed to be registered in DB may be the main problem in my case.

Is it possible to make the registration of new users automatic when they log in through CAS pls ?

**Comment by nicocasel** [comment]
"Try logging in in your CAS server, then going to the login screen of your board (not the index, but the /ucp.php?mode=login) and then clicking "Login"!"
@Getekid : thanks for this precision but it does not solve the problem. Indeed, after clicking "Login" I appear as registered on the forum, but it is thanks to... the "db" mode actually.

@Jhereck: as @Getekid said before, new users automatically registered will be next step of his work :-)

**Comment by Getekid** [comment]
Hello, indeed this is the most user-friendly way, this is the reason I mentioned this way as a **temporary workaround** and **messy** ! It's just that I haven't yet found a way to successfully implement it **yet**. I will keep you updated on the issue.

PS: For aditional user-friendliness, I also plan to hide the user/pass textareas and just keep the button.

**Comment by Jhereck** [comment]
Can't wait for the automatic DB user registration when connecting with CAS !! :)

**Comment by Jhereck** [comment]
Hi ! 

So any news from an update to automaticly register users connecting with CAS to the forum database ?

Thanks ! :)

**Comment by Getekid** [comment]
Hi, development has been slow lately but this feature won't take much.

Still, this issue is for the plugin's functionality. Please open a new feature request in order to discuss more about it.

Thanks

**Comment by Getekid** [comment]
Closing this as 
* Automatic DB user registration was taken care of on Issue #5 
* Apart from the workaround, instant login will be taken care of on Issue #4
