### ISSUE TITLE
Enable ECAS login with phpBB forum

### ISSUE THREAD

**Issue by nicocasel** [Getekid/phpbb3-CAS-Auth-plugin#4]
@Getekid
As you suggest in your last post from issue "Still doesn't work on fresh install", I open a specific issue for enabling ECAS login with phpBB forum.

Would it be possible to have this way of login: after logging in the CAS server, user is redirected to the forum login screen (or whatever forum screen) and s/he already appear as registered (with his/her login id displayed in the upper right-hand corner); without forcing him/her to click one more time on "login".

**Comment by Getekid** [comment]
**Temporary workaround**

On [line 92](https://github.com/Getekid/phpbb3-CAS-Auth-plugin/blob/master/getekid/cas/auth/provider/cas.php#L92) add the following line:

`phpCAS::checkAuthentication();`

This way after the user will require to press the login button maximum **twice** (3 times if the user does not exist).

In the meantime a fix is being worked on.

**Comment by Getekid** [comment]
**Temporary workaround**

On [line 92](https://github.com/Getekid/phpbb3-CAS-Auth-plugin/blob/master/getekid/cas/auth/provider/cas.php#L92) add the following line:

`phpCAS::isAuthenticated();`

This way after the user will require to press the login button maximum **twice** (3 times if the user does not exist).

In the meantime a fix is being worked on.

**Comment by Getekid** [comment]
**Temporary workaround**

On [line 92 of cas.php](https://github.com/Getekid/phpbb3-CAS-Auth-plugin/blob/master/getekid/cas/auth/provider/cas.php#L92) add the following line:

`phpCAS::isAuthenticated();`

This way after the user will require to press the login button maximum **twice** (3 times if the user does not exist).

In the meantime a fix is being worked on.
